### PR TITLE
Removed the use of internal eigen.

### PR DESCRIPTION
**Pull request by knzo25**
## PR Type

- Improvement

## Related Links

 - [Ticket](https://tier4.atlassian.net/browse/T4PB-17687)

## Description
In order to use Eigen 3.4 the authors added Eigen as a internal dependency.
However, it caused conflicts with the system Eigen making development difficult and prone to even runtime errors.

Here we removed the internal version and the 3.4-only featured (we plan to migrate to humble so we will have a newer version anyways).

## Review Procedure

Using any bag verify that lidartag still works (also that it compiles).

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]
- [ ] (When added something to `.repos`) Check if proper access rights are set

## CI Checks

- **vcs import**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by yabuta — APPROVED** [review]
LGTM

**Comment by aohsato** [comment]
@knzo25 Let me check, you just commented out unused method depended on Eigen 3.4, right?

**Comment by knzo25** [comment]
The code that required the >3.4 API was actually unused so I just commented it.
Removing the "internal" version did not cause any other issues in the tests I was doing with the XX1 data

**Comment by aohsato** [comment]
@knzo25 Good, thanks!

**Review by aohsato — APPROVED** [review]

**Comment by knzo25** [comment]
:tada:

**Pull request merged**
